#!/bin/bash
set -e

BATCH1="database/supabase-postgres-best-practices,database/neon-instagres,database/using-neon,database/postgres-schema-design,analytics/google-analytics,ai-maestro/planning,ai-maestro/agent-management,ai-maestro/memory-search,ai-maestro/agent-messaging,ai-maestro/graph-query,ai-maestro/docs-search,ai-research/agents-langchain,ai-research/claude-code-guide,ai-research/agent-memory-systems,ai-research/context7-auto-research,ai-research/ai-agents-architect,ai-research/prompt-engineering,ai-research/agents-crewai,ai-research/agents-autogpt,ai-research/prompt-engineer"

BATCH2="ai-research/agent-tool-builder,ai-research/agent-manager-skill,ai-research/langgraph,ai-research/agent-evaluation,ai-research/autonomous-agents,ai-research/prompt-engineering-guidance,ai-research/agents-llamaindex,ai-research/conversation-memory,ai-research/agent-memory-mcp,ai-research/research-engineer,ai-research/prompt-engineering-instructor,ai-research/rag-engineer,ai-research/qa-test-planner,ai-research/context-window-management,ai-research/prompt-engineering-dspy,ai-research/autonomous-agent-patterns,ai-research/gemini,ai-research/data-processing-ray-data,ai-research/computer-use-agents,ai-research/dispatching-parallel-agents"

BATCH3="ai-research/data-processing-nemo-curator,ai-research/voice-ai-development,ai-research/jira,ai-research/emerging-techniques-long-context,ai-research/distributed-training-accelerate,ai-research/loki-mode,ai-research/crewai,ai-research/evaluation-lm-evaluation-harness,ai-research/distributed-training-pytorch-lightning,ai-research/emerging-techniques-knowledge-distillation,ai-research/voice-agents,ai-research/rag-qdrant,ai-research/fine-tuning-peft,ai-research/behavioral-modes,ai-research/distributed-training-pytorch-fsdp,ai-research/distributed-training-megatron-core,ai-research/subagent-driven-development,ai-research/emerging-techniques-model-merging,ai-research/emerging-techniques-speculative-decoding,ai-research/llm-app-patterns"

BATCH4="ai-research/perplexity,ai-research/distributed-training-deepspeed,ai-research/ml-paper-writing,ai-research/prompt-engineering-outlines,ai-research/parallel-agents,ai-research/prompt-library,ai-research/inference-serving-vllm,ai-research/rag-implementation,ai-research/distributed-training-ray-train,ai-research/inference-serving-llama-cpp,ai-research/evaluation-bigcode-evaluation-harness,ai-research/emerging-techniques-moe-training,ai-research/fine-tuning-unsloth,ai-research/rag-chroma,ai-research/datadog-cli,ai-research/emerging-techniques-model-pruning,ai-research/inference-serving-tensorrt-llm,ai-research/infrastructure-modal,ai-research/mlops-mlflow,ai-research/prompt-caching"

BATCH5="ai-research/fine-tuning-llama-factory,ai-research/observability-langsmith,ai-research/rag-faiss,ai-research/infrastructure-lambda-labs,ai-research/multimodal-whisper,ai-research/inference-serving-sglang,ai-research/optimization-gguf,ai-research/observability-phoenix,ai-research/fine-tuning-axolotl,ai-research/evaluation-nemo-evaluator,ai-research/mlops-weights-and-biases,ai-research/multimodal-audiocraft,ai-research/infrastructure-skypilot,ai-research/mlops-tensorboard,ai-research/multimodal-stable-diffusion,ai-research/rag-pinecone,ai-research/langfuse,ai-research/optimization-flash-attention,ai-research/model-architecture-mamba,ai-research/model-architecture-nanogpt"

BATCH6="ai-research/safety-alignment-nemo-guardrails,ai-research/optimization-gptq,ai-research/rag-sentence-transformers,ai-research/gepetto,ai-research/model-architecture-litgpt,ai-research/optimization-bitsandbytes,ai-research/post-training-trl-fine-tuning,ai-research/tokenization-huggingface-tokenizers,ai-research/post-training-grpo-rl-training,ai-research/post-training-openrlhf,ai-research/model-architecture-rwkv,ai-research/optimization-hqq,ai-research/mechanistic-interpretability-nnsight,ai-research/multimodal-clip,ai-research/multimodal-segment-anything,ai-research/openai-docs,ai-research/optimization-awq,ai-research/post-training-simpo,ai-research/mechanistic-interpretability-transformer-lens,ai-research/safety-alignment-constitutional-ai"

BATCH7="ai-research/mechanistic-interpretability-pyvene,ai-research/mechanistic-interpretability-saelens,ai-research/multimodal-llava,ai-research/model-architecture-torchtitan,ai-research/post-training-miles,ai-research/safety-alignment-llamaguard,ai-research/multimodal-blip-2,ai-research/post-training-slime,ai-research/post-training-torchforge,ai-research/post-training-verl,ai-research/tokenization-sentencepiece,ai-research/deep-research-notebooklm,web-data/scrape,web-data/data-feeds,web-data/search,web-data/bright-data-best-practices,web-data/bright-data-mcp,web-data/design-mirror,scientific/markitdown,scientific/generate-image"

BATCH8="scientific/scientific-critical-thinking,scientific/scientific-slides,scientific/plotly,scientific/market-research-reports,scientific/literature-review,scientific/scientific-writing,scientific/statistical-analysis,scientific/scientific-visualization,scientific/pptx-posters,scientific/scientific-brainstorming,scientific/citation-management,scientific/matplotlib,scientific/exploratory-data-analysis,scientific/perplexity-search,scientific/scientific-schematics,scientific/pymoo,scientific/scikit-learn,scientific/paper-2-web,scientific/peer-review,scientific/research-lookup"

BATCH9="scientific/networkx,scientific/latex-posters,scientific/pubmed-database,scientific/statsmodels,scientific/research-grants,scientific/seaborn,scientific/hypothesis-generation,scientific/geopandas,scientific/clinical-reports,scientific/treatment-plans,scientific/clinical-decision-support,scientific/shap,scientific/pytorch-lightning,scientific/denario,scientific/openalex-database,scientific/uspto-database,scientific/sympy,scientific/modal,scientific/polars,scientific/scanpy"

BATCH10="scientific/scholar-evaluation,scientific/biopython,scientific/qutip,scientific/venue-templates,scientific/dnanexus-integration,scientific/pyhealth,scientific/alphafold-database,scientific/simpy,scientific/pydicom,scientific/pymc,scientific/bioservices,scientific/anndata,scientific/biomni,scientific/get-available-resources,scientific/kegg-database,scientific/torch_geometric,scientific/uniprot-database,scientific/aeon,scientific/astropy,scientific/deepchem"

BATCH11="scientific/pdb-database,scientific/transformers,scientific/clinpgx-database,scientific/clinvar-database,scientific/datacommons-client,scientific/drugbank-database,scientific/gene-database,scientific/gget,scientific/histolab,scientific/biorxiv-database,scientific/dask,scientific/datamol,scientific/deeptools,scientific/geo-database,scientific/opentargets-database,scientific/pennylane,scientific/pyopenms,scientific/clinicaltrials-database,scientific/fluidsim,scientific/gtars"

BATCH12="scientific/protocolsio-integration,scientific/torchdrug,scientific/umap-learn,scientific/zarr-python,scientific/ensembl-database,scientific/hmdb-database,scientific/medchem,scientific/neurokit2,scientific/pytdc,scientific/qiskit,scientific/rdkit,scientific/reactome-database,scientific/string-database,scientific/benchling-integration,scientific/ena-database,scientific/etetoolkit,scientific/gwas-database,scientific/latchbio-integration,scientific/metabolomics-workbench-database,scientific/omero-integration"

BATCH13="scientific/pydeseq2,scientific/vaex,scientific/zinc-database,scientific/adaptyv,scientific/brenda-database,scientific/cellxgene-census,scientific/chembl-database,scientific/cirq,scientific/cobrapy,scientific/diffdock,scientific/fda-database,scientific/geniml,scientific/hypogenic,scientific/matchms,scientific/neuropixels-analysis,scientific/pathml,scientific/pylabrobot,scientific/pymatgen,scientific/pysam,scientific/scikit-bio"

BATCH14="scientific/scikit-survival,scientific/scvi-tools,scientific/stable-baselines3,scientific/cosmic-database,scientific/labarchive-integration,scientific/molfeat,scientific/opentrons-integration,scientific/pubchem-database,scientific/arboreto,scientific/esm,scientific/flowio,scientific/lamindb,scientific/pufferlib,workflow-automation/workflow-automation,workflow-automation/planning-with-files,workflow-automation/github-workflow-automation,workflow-automation/trigger-dev,workflow-automation/inngest,workflow-automation/zapier-make-patterns,workflow-automation/yeet"

BATCH15="workflow-automation/dependabot-review,sentry/find-bugs,sentry/code-review,sentry/deslop,sentry/commit,sentry/create-pr,sentry/iterate-pr,railway/database,railway/deploy,railway/service,railway/templates,railway/railway-docs,railway/deployment,railway/metrics,railway/domain,railway/environment,railway/new,railway/status,railway/projects,productivity/file-organizer"

BATCH16="productivity/invoice-organizer,productivity/humanizer,productivity/brainstorming,productivity/meeting-insights-analyzer,productivity/game-changing-features,productivity/planning-with-files,productivity/notebooklm,productivity/notion-knowledge-capture,productivity/requirements-clarity,productivity/plan-writing,productivity/writing-rules,productivity/doc-coauthoring,productivity/notion-research-documentation,productivity/skill-judge,productivity/notion-template-business,productivity/skill-developer,productivity/kaizen,productivity/concise-planning,productivity/skill-creator,productivity/linear"

BATCH17="productivity/notion-spec-to-implementation,productivity/personal-tool-builder,productivity/writing-plans,productivity/obsidian-clipper-template-creator,productivity/writing-skills,productivity/crafting-effective-readmes,productivity/executing-plans,productivity/commit-work,productivity/notion-meeting-intelligence,productivity/ship-learn-next,productivity/raffle-winner-picker,productivity/naming-analyzer,productivity/reducing-entropy,productivity/nowait,productivity/address-github-comments,productivity/think-tank,productivity/deadline-prep,enterprise-communication/excel-analysis,enterprise-communication/email-composer,enterprise-communication/brand-guidelines"

BATCH18="enterprise-communication/internal-comms,enterprise-communication/quality-documentation-manager,enterprise-communication/telegram-bot-builder,enterprise-communication/frontend-to-backend-requirements,enterprise-communication/data-privacy-compliance,enterprise-communication/information-security-manager-iso27001,enterprise-communication/backend-to-frontend-handoff-docs,enterprise-communication/writing-clearly-and-concisely,enterprise-communication/gdpr-dsgvo-expert,enterprise-communication/risk-management-specialist,enterprise-communication/discord-bot-architect,enterprise-communication/twilio-communications,enterprise-communication/professional-communication,enterprise-communication/telegram-mini-app,enterprise-communication/session-handoff,enterprise-communication/slack-bot-builder,enterprise-communication/daily-meeting-update,enterprise-communication/fda-consultant-specialist,enterprise-communication/isms-audit-expert,enterprise-communication/difficult-workplace-conversations"

BATCH19="enterprise-communication/feedback-mastery,enterprise-communication/regulatory-affairs-head,enterprise-communication/internal-comms-anthropic,enterprise-communication/slack-gif-creator,enterprise-communication/mdr-745-specialist,enterprise-communication/qms-audit-expert,enterprise-communication/quality-manager-qms-iso13485,enterprise-communication/capa-officer,enterprise-communication/quality-manager-qmr,enterprise-communication/internal-comms-community,git/commit-smart,git/git-context-controller,security/api-security-best-practices,security/vulnerability-scanner,security/top-web-vulnerabilities,security/security-best-practices,security/sql-injection-testing,security/webapp-testing,security/wordpress-penetration-testing,security/red-team-tools"

BATCH20="security/pentest-checklist,security/xss-html-injection,security/broken-authentication,security/html-injection-testing,security/cloud-penetration-testing,security/security-threat-model,security/pentest-commands,security/red-team-tactics,security/scanning-tools,security/ssh-penetration-testing,security/ethical-hacking-methodology,security/file-uploads,security/api-fuzzing-bug-bounty,security/smtp-penetration-testing,security/burp-suite-testing,security/linux-privilege-escalation,security/privilege-escalation-methods,security/active-directory-attacks,security/security-ownership-map,security/windows-privilege-escalation"

BATCH21="security/metasploit-framework,security/sqlmap-database-pentesting,security/file-path-traversal,security/idor-testing,security/aws-penetration-testing,security/wireshark-analysis,security/shodan-reconnaissance"

for i in $(seq 1 21); do
  eval "BATCH=\$BATCH$i"
  echo ""
  echo "=== Installing batch $i ==="
  npx --ignore-scripts claude-code-templates@latest --skill "$BATCH" 2>&1
done
