const env = (key: string) => import.meta.env[key] === 'true';

export const FEATURE_FLAGS = {
    // Agent System
    ENABLE_AGENT_CLASSES: env('VITE_FEATURE_AGENT_CLASSES'),
    ENABLE_TYPED_HANDLERS: env('VITE_FEATURE_TYPED_HANDLERS'),
    ENABLE_EVENT_BUS: env('VITE_FEATURE_EVENT_BUS'),

    // Audio/Visual
    ENABLE_ADVANCED_AUDIO: env('VITE_FEATURE_ADVANCED_AUDIO'),
    ENABLE_SHADER_GLOW: env('VITE_FEATURE_SHADER_GLOW'),

    // API
    USE_V2_ENDPOINTS: env('VITE_FEATURE_V2_ENDPOINTS'),
    USE_BATCH_REQUESTS: env('VITE_FEATURE_BATCH_REQUESTS'),

    // Debug
    ENABLE_AGENT_DEBUG_PANEL: env('VITE_FEATURE_AGENT_DEBUG_PANEL'),
    ENABLE_PERFORMANCE_MONITORING: env('VITE_FEATURE_PERFORMANCE_MONITORING'),
};

export function isFeatureEnabled(feature: keyof typeof FEATURE_FLAGS): boolean {
    return FEATURE_FLAGS[feature];
}
